export  { default as Dashboard } from "./dashboard/Dashboard";
export { default as Courses } from "./courses/Courses"
export { default as Students } from './students/Students'
export { default as Teachers } from './teachers/Teachers'
export { default as StudentAttendance } from './attendance/StudentAttendance'
export { default as AddStudent } from './students/AddStudent'
export { default as Login } from './login/Login'
export { default as Admins } from './admins/Admins'
export {default as RegisterAdmin} from './admins/RegisterAdmin'
export {default as AcademicYears} from './academin-year/AcademicYears'
export {default as RegisterAcademicYear} from './academin-year/RegisterAcademicYear'
export {default as AddTeacher} from './teachers/AddTeacher'
export {default as DeleteSingleStudent } from './students/DeleteSingleStudent'
export {default as RegisterStudentClass } from './classes/RegisterStudentClass'
export {default as RegisterNewSection } from './sections/RegisterNewSection'
export {default as DeleteSingleTeacher } from './teachers/DeleteSingleTeacher'
export {default as RegisterCourse } from './courses/RegisterCourse'
export {default as EditSingleStudent} from './students/EditSingleStudent'
export {default as SingleTeacherProfile} from './teachers/SingleTeacherProfile'
export {default as EditTeacher} from './teachers/EditTeacher'
export {default as SingleClass} from './classes/SingleClass'
export {default as SingleClassEdit} from './classes/SingleClassEdit'
export {default as RegisterRoutine} from './Routines/RegisterRoutine'
export {default as SingleSalaryTemplate} from './finance/SingleSalaryTemplate'
export {default as ViewSalaries} from './finance/ViewSalaries'
export {default as DeleteSingleClass} from './classes/DeleteSingleClass'
export {default as Sections} from './sections/Sections'
export {default as Payment} from './payment/Payment'
export {default as Transactions} from './payment/Transactions'
export {default as GetFee} from './students/GetFee'
export {default as Employees } from './employee/Employees'
export {default as AddSingleEmployee} from './employee/AddSingleEmployee'
export {default as AddSingleHostel} from './hostel/AddSingleHostel'
export {default as Transports } from './transports/Transports'
export {default as AddSingleRoute} from './transports/AddSingleRoute'
export {default as AddSinlgeResult} from './results/AddSingleResult'
export {default as Hostels} from './hostel/Hostels'
export {default as SingleHostel} from './hostel/SingleHostel'
export {default as AvailableSeats} from './hostel/AvailableSeats'
export {default as BulkUpload} from './students/BulkUpload'
export {default as AddExam} from './exam/AddExam'
export {default as ViewExam} from './exam/ViewExam'
export {default as CheckSingleResult} from './results/CheckSingleResult'
export {default as AddSingleVehicle} from './transports/AddSingleVehicle'
export {default as ViewSingeRoute} from './transports/ViewSingeRoute'
export {default as ViewSingleSection} from './sections/ViewSingleSection'
export {default as DeleteSingleSection} from './sections/DeleteSingleSection'
export {default as EditSingleSection} from './sections/EditSingleSection'
export {default as DeleteSingleEmmployee} from './employee/DeleteSingleEmployee'
export {default as ViewSingleEmployee} from './employee/ViewSingleEmployee'
export {default as EditSingleEmployee} from './employee/EditSingleEmployee'
export {default as SingleCourse} from './courses/SingleCourse'
export {default as DeleteSingleCourse} from './courses/DeleteSingleCourse'
export {default as SingleStudent} from './students/SingleStudent'
export {default as SingleCourseEdit} from './courses/SingleCourseEdit'
export {default as SingleRoom} from './hostel/SingleRoom'
export {default as EditSingleRoom} from './hostel/EditSingleRoom'
export {default as DeleteSingleHostel} from './hostel/DeleteSingleHostel'
export {default as DeleteSingleRoom} from './hostel/DeleteSingleRoom'
export {default as PaymentFor} from './payment/PaymentFor'
export {default as GetFeeDistrubution} from './payment/GetFeeDistribution'
export {default as ViewFeeDistribution} from './payment/ViewFeeDistribution'
export {default as ViewSingleFeeDistribution} from './payment/ViewSingleFeeDistribution'
export {default as SelectPayment} from './payment/SelectPayment'
export {default as GetReportByType} from './report/GetReportByType'
export {default as IncomeReport} from './report/IncomeReport'
export {default as SingleIncomeReport} from './report/SingleIncomeReport'
export {default as EndPoints} from './admins/EndPoints'
export {default as ViewSingleExam} from './exam/ViewSingleExam'
export {default as DeleteSingleExam} from './exam/DeleteSingleExam'
export {default as GetCertificate} from './results/GetSertificate'
export {default as ViewPermission } from './admins/ViewPermission'
export {default as RegisterPermission} from './admins/RegisterPermission'
export {default as GivePermission} from './admins/GivePermission'
export {default as GetRoleBasedPermission} from './admins/GetRoleBasedPermission'
export {default as ViewSingleTransaction} from './payment/ViewSingleTransaction'
export {default as AddExpense} from './finance/AddExpense'
export {default as AddStaff} from './staff/AddStaff'
export {default as ViewStaff} from './staff/ViewStaffs'
export {default as DeleteSingleDistribution} from './payment/DeleteSingleDistribution'
export {default as DeleteSingleTransaction} from './payment/DeleteSingleTransaction'
export {default as ViewExpenses} from './finance/ViewExpenses'
export {default as ViewSingleExpense} from './finance/ViewSingleExpense'
export {default as DeleteSingleExpense} from './finance/DeleteSingleExpense'
export {default as DeleteSingleSalary} from './finance/DeleteSingleSalary'
export {default as ViewSingleIncomeReport} from './finance/ViewSingleIncomeReport'
export {default as DeleteSingleStaff} from './staff/DeleteSingleStaff'
export {default as GenerateSalarySheet} from './finance/GenerateSalarySheet'
export {default as MonthlyExpense} from './report/MonthlyExpense'
export {default as MonthlySalary} from './report/MonthlySalary'
export {default as ViewUsers} from './staff/ViewUsers'
export {default as Pay} from './finance/Pay'
export {default as SinglePayment} from './finance/SinglePayment'